# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0003_auto_20170503_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
