# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0004_order_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-weekNumber', 'user']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='changed',
        ),
    ]
