# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0005_auto_20170504_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
