# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import friday_meals.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0006_submitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Category title'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Is it available'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.ImageField(blank=True, upload_to='meal_images', verbose_name='Images of the meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Meal title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekNumber',
            field=models.IntegerField(default=friday_meals.utils.get_current_week),
        ),
    ]
