# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0007_auto_20170510_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
