# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0008_auto_20170510_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
