# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0010_auto_20170510_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
