# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0013_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
