# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import friday_meals.utils


class Migration(migrations.Migration):

    dependencies = [
        ('friday_meals', '0014_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitorder',
            options={'ordering': ['-weekNumber']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=friday_meals.utils.get_current_date),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
